### ISSUE TITLE
.zip file not uncompressing properly.

### ISSUE THREAD

**Issue by quade-ksp** [TeleIO/Telemachus-1#12]
.zip file downloads, but doesn't uncompress properly.  ALL files end up in GameData folder with no underlying folder structure.

<img width="915" alt="Screen Shot 2019-03-15 at 12 47 30 PM" src="https://user-images.githubusercontent.com/35043614/54458250-9ec8dc00-4720-11e9-951d-c3ae1fcfa15c.png">

**Comment by dsolmann** [comment]
I think we'll able to fix that by manually compressing ZIP-Files, currently, we are using the fully-automated pipeline.

**Comment by quade-ksp** [comment]
Looking forward to it.  Thanks.

**Comment by dsolmann** [comment]
Fixed in Telemachus Gyrfalcon (v1.7)/
