### ISSUE TITLE
CKAN indexing

### ISSUE THREAD

**Issue by DasSkelett** [TeleIO/Telemachus-1#15]
Someone just asked for a currently maintained Telemachus fork on CKAN's irc. A little search brought me here.
I realized that Telemachus Reborn is currently **not** indexed on CKAN, despite having even 2 valid looking .netkans in the repo.

I searched here, the forum thread, the CKAN repos, the opt-out list, but I can find no word about this mod's indexing, or if you requested a de-indexing in the past.

Can you tell me the reason this mod is not indexed? I'm sorry if you stated it already somewhere, but as I said, I can't find anything. Thanks!

**Comment by dsolmann** [comment]
Hello, @DasSkelett. I think, that I've started the process of publishing this fork on CKAN, but somewhere I've got a problem and abandoned this idea. I would be very grateful if you would help me with CKAN.

**Comment by DasSkelett** [comment]
Of course I'll be happy to help you.

One question to get started:
You have a AVC .version file in your repository, but not bundled in the release zip.
If you bundle it, you could use it to tell CKAN the KSP version compatibility.
I think it's easier for you if you only have to update the .version file, and you don't have to bother with the version override in the netkan after each KSP update.

**Comment by dsolmann** [comment]
@DasSkelett, thx. I will bundle it.

**Comment by DasSkelett** [comment]
Okay. I'm going to open a PR in the KSP-CKAN/NetKAN repo now so your mod will be indexed.
I've made small adjustments to your .netkan, [see here](https://github.com/DasSkelett/NetKAN/blob/da675b0cd1011c7bfa468152ceac192de1363e2c/NetKAN/TelemachusReborn.netkan).
I didn't create a PR here to update your .netkan file, because there might be further changes needed, we'll see in the KSP-CKAN/NetKAN PR.

I haven't removed the version override  yet, so the current release can be indexed properly too, even without the .version file.

**Comment by DasSkelett** [comment]
https://github.com/KSP-CKAN/NetKAN/pull/7209 is now merged :tada:
Telemachus Reborn is now indexed on the CKAN.
![grafik](https://user-images.githubusercontent.com/28812678/58482905-94cf4a80-815f-11e9-9006-909e69cf9c60.png)

Please keep an eye out when you release the next version, if it works correctly with the .version file. If not, just contact us, or try to create a PR at https://github.com/KSP-CKAN/NetKAN/ yourself, if you want.

**Comment by dsolmann** [comment]
Thank you very much, @DasSkelett!
