### ISSUE TITLE
Constant stream of NULLREFS if installed with JNSQ planet pack

### ISSUE THREAD

**Issue by StoneBlue** [TeleIO/Telemachus-1#19]
So here's a question for anyone who may know, not just @DanGSun ...
How difficult would it be to edit the code, to have an option to turn off all the mapping features for Telemachus, yet leave everything else working?

It seems Telemachus just continually throws nullrefs when you are using any planet pack or maybe even rescaled systems... at least it is specifically with JNSQ...anything but stock system...
Making Telemachus *completely* useless in any install other than stock Kerbol system... :(

I assume this is because of the hard-coded dependency on a site hosting *only* stock Kerbol system maps... vOV

Telemachus throws these NULLREFS during game loading, while JNSQ textures are loading, and they continue on as a constant stream of exceptions in-game:

`[EXC 01:37:04.228] NullReferenceException: Object reference not set to an instance of an object
	Telemachus.TelemachusBehaviour.Update ()`

**Comment by sidrus** [comment]
I will have a look at this.

**Comment by sidrus** [comment]
Are you still experiencing this issue?  I've got the latest version of JNSQ and Telemachus installed and I can't replicate the errors.  I'll keep digging to see if I can replicate the issue, but if you have a list of mods currently installed that may help.

**Comment by StoneBlue** [comment]
I'll reinstall JNSQ/Telemachus on a fresh 1.9.1 install today, and check.

Since we're talking JNSQ/Telemachus, and it looks like several of you are now active over the past couple of days, has anyone looked into having Telemachus mapping work with the latest *beta* version of the JNSQ packs on the new KerbalMaps server?
I poked at the Telemachus code last week, and I couldnt see anything *anywhere*, where it would a simpple variable or line change... vOv

Relevant thread is here. not sure if the link for the completed JNSQ maps is in the OP, or in the last couple weeks of posts.
https://forum.kerbalspaceprogram.com/index.php?/topic/181688-kerbal-maps-is-back-sort-of/

Go ahead and split this off to a seperate issue, if need be, or lmk and I will create one, with moar detail. ;)

**Comment by StoneBlue** [comment]
Actually, here is the specific post in the thread, with the *beta* link that includes complete JNSQ maps:
https://forum.kerbalspaceprogram.com/index.php?/topic/181688-kerbal-maps-is-back-sort-of/&do=findComment&comment=3756346

And if any code needs to changed in Telemachus to use JNSQ *or ANY other pack from there*,
maybe changes could/should be made to future-proof and make it easier for Telemachus to use different packs from there? (like either a UI or config/settings file for Telemachus to switch between packs, rather than having something that would need to changed, being hard-coded?) vOv
i know there was uncomfirmed comments/discussion made about maybe adding some other popular planet packs to the KM catalog, in the future... vOv

**Comment by sidrus** [comment]
I will create a new ticket for the mapping stuff.  I poked around in there a bit and it looks like it will be non-trivial to get that updated; but, it's necessary in my opinion.  I think it would be best to track that in its own issue, though.

**Comment by StoneBlue** [comment]
So, yeah... I havent done a lot in this JNSQ install, but not a peep out of Telemachus this time...
No NULLREFs from *anything*... with a couple dozen mods installed.

I guess we can close this one out.

**Comment by StoneBlue** [comment]
hit the wrong button submitting above comment :man_facepalming: 
Closing issue.
