### ISSUE TITLE
Is this project finished (and just being updated) or in progress? How can I use it in the game?

### ISSUE THREAD

**Issue by kawarantik** [TeleIO/Telemachus-1#23]
Sorry, I really tried to figure it out, but I'm not 100% sure how to actually install this (if it's usable). The readme links to the main telemachus github, which hasn't been updated since like 2017. Should I download that one instead, or is the readme outdated or something?

EDIT 1: I just downloaded the master and put it in my GameData like you do with normal mods. Launching to see if it works.

EDIT 2: The game tells me that I have an incompatible dll, so I figured that the "dependencies" probably shouldn't be installed if I already have the new versions of those two dependencies.

EDIT 3: After removing dependencies, it seems like there is no error with the game, but I absolutely can't find any info relating to Telemachus, like a button to get it set up. So I guess it didn't install correctly. I'll just wait for a reply.

**Comment by todiwan** [comment]
I just downloaded the master and put it in my GameData like you do with normal mods. Launching to see if it works.

**Comment by dsolmann** [comment]
The project is finished. I'm just rebuilding it for new versions and fixing some bugs.

**Comment by dsolmann** [comment]
If you want to write your own Web-Interface or use it as API, I'd suggest using kRPC.
