### ISSUE TITLE
THIS PROJECT NEEDS MAINTAINER

### ISSUE THREAD

**Issue by dsolmann** [TeleIO/Telemachus-1#24]
Hey guys. I am not a C# programmer and I never was one. I am Python Developer. And I don't have enough time even to fix some autobuilding issues with AppVeyor. I will be happy to add anyone as maintainer to this organization to continue work at Telemachus. Thanks to everyone, who still hold with Telemachus)

**Comment by sidrus** [comment]
I wouldn't mind helping out.

**Comment by dsolmann** [comment]
> I wouldn't mind helping out.

Thank you for your commitment! Then, I'll add you as contributor. Can you start resolving issues, please?
