### ISSUE TITLE
Can't seem to install it on my ksp

### ISSUE THREAD

**Issue by SpoOkyJelle** [TeleIO/Telemachus-1#28]
The parts load but i cant seem to right click on anything to open the link?

**Comment by StoneBlue** [comment]
Hmm.. the mod doesnt have any dependencies, so its a relatively easy install.
You should just be able to extract the .zip to your GameData, and it should work.
Can you post a screenshot of the contents of your Gamedata folder?

**Comment by sidrus** [comment]
@SpoOkyJelle Try downloading and installing the latest release.  It should be available on CKAN or you can manually download it here: https://github.com/TeleIO/Telemachus-1/releases/tag/1.7.56.  I think that will get you going.  If not, let me know and I'll try to help you further.

You can also jump in the Discord channel if you'd like :)

**Comment by sidrus** [comment]
I haven't heard back on this issue.  I hope you got the issue resolved.  :)  If you're still having issues, please feel free to reopen the ticket.
