### ISSUE TITLE
No "Open Link" Available on right click

### ISSUE THREAD

**Issue by nwalty** [TeleIO/Telemachus-1#31]
I am sure I have goofed something up along the way, but I cant seem to figure out what. I have the parts available but when I right click on them there isn't an "open link" option available.

**Comment by sidrus** [comment]
Hi - just a quick question: if you look in `\GameData\Telemachus\Plugins` do you see `Telemachus.dll`?

**Comment by nwalty** [comment]
I am seeing  \Plugins\PluginData\Telemachus\and then a list of files like css and .htmls, no .dll files

**Comment by sidrus** [comment]
Could you try removing your Telemachus directory from the `GameData\` and reinstalling it with the latest build from https://github.com/TeleIO/Telemachus-1/releases/tag/untagged-adda40278628d9c161c6

It sounds like you may be missing the plugin DLL.  The latest build should work for you.

**Comment by nwalty** [comment]
that url leads to a 404 error

**Comment by nwalty** [comment]
is it the white-raven release?

**Comment by nwalty** [comment]
> is it the white-raven release?

I think i found it, Telemachus Reborn v1.7 - Gyrfalcon (KSPv1.7.0), it has the DLL in it. gonna run it now.

**Comment by sidrus** [comment]
weird.  I'm still getting my bearings on the release workflow for this project.  I'll see if I can fix that url

**Comment by sidrus** [comment]
Turns out I hadn't published it.

https://github.com/TeleIO/Telemachus-1/releases/tag/1.7.35

**Comment by nwalty** [comment]
I have downloaded but have not extracted it yet. When I do I will touch base. Thanks!

Nick Walton
n.walton@live.com
701-367-2957

________________________________

**Comment by sidrus** [comment]
Sounds good!  I also have a discord going at https://discord.gg/3f7JNH if you'd like to pop in there and chat.

**Comment by sidrus** [comment]
Based on our discussion in discord, I'm going to close out this ticket.
