### ISSUE TITLE
1.7.35 release has no version file

### ISSUE THREAD

**Issue by HebaruSan** [TeleIO/Telemachus-1#33]
The latest release does not contain a version file:

https://github.com/TeleIO/Telemachus-1/releases/tag/1.7.35

This has caused its CKAN entry to be marked as compatible with all KSP versions, which it presumably is not:

https://github.com/KSP-CKAN/CKAN-meta/commit/8796185149c016b634149dc96c1de5d1b52bb019

Found while investigating KSP-CKAN/NetKAN#7810.

Tagging @sidrus who presumably has some involvement with this project, as well as @dsolmann whose name is on the release.

**Comment by HebaruSan** [comment]
Ahh, the previous 1.7.0 version also didn't have one, but we set up an override for that release. I guess we can do that again, but it would be better to get the version file included in the download.

**Comment by sidrus** [comment]
I agree; I'd rather get the version file in there.  I will get it all sorted and update my PR.  This is my first time working through this :)

**Comment by HebaruSan** [comment]
1.7.45 looks good, closing.
