### ISSUE TITLE
Add @sidrus to SpaceDock's page.

### ISSUE THREAD

**Issue by dsolmann** [TeleIO/Telemachus-1#42]
https://spacedock.info/mod/2012/Telemachus%20Reborn/

**Comment by sidrus** [comment]
Not sure how to go about getting this one done :)  Any tips heh

**Comment by dsolmann** [comment]
Make yours account there, tell me your username &  I'll add you

**Comment by sidrus** [comment]
My user name is: sidrus

**Comment by dsolmann** [comment]
OK, I've send you a request

**Comment by sidrus** [comment]
completed - closing the ticket.  Thanks!
