### ISSUE TITLE
Startup crash since install, isolated this as crashing.

### ISSUE THREAD

**Issue by cheezecakes** [TeleIO/Telemachus-1#43]
removed all mods but this one and cleared cache and it still causes startup crashes. Currently using steam version KSP-dlc, windows 10

crashes during load-up at /sgripgrip

**Comment by Row-Bear** [comment]
Which KSP version and Telemachus version do you have?

**Comment by cheezecakes** [comment]
winplayer x64 en-us 1.9.1.2788
1.9.1 making history
1.4.1 breaking ground

**Comment by cheezecakes** [comment]
from ckan 1.7.56

**Comment by Row-Bear** [comment]
I haven't been able to replicate this issue, for me it starts up all the way into flight/orbit.
Also on windows 10, same KSP versions and Telemachus from CKAN.
Can you try with a manual install from https://github.com/TeleIO/Telemachus-1/releases/tag/1.7.56
or https://github.com/TeleIO/Telemachus-1/releases/tag/1.7.45 ?

**Comment by cheezecakes** [comment]
Is there a log i can produce? i've cleared both ckan cache and gamedata directories. tried different versions, available through ckan. will attempt above links and get back to you. thanks.

**Comment by sidrus** [comment]
Hi Cheezekakes!  I run a pretty similar setup as you; Win 10, Steam client and all the DLCs.  I will try to replicate the error.

The mod doesn't produce any logs to the disk, but I will be fixing that soon too :)

**Comment by sidrus** [comment]
One log that may be helpful is located at `steamapps\common\Kerbal Space Program\KSP.log` - Startup errors might show up in there.

**Comment by cheezecakes** [comment]
tried with a clean install(started fine) and only telemachus installed log stops here

[LOG 20:55:40.116] PartLoader: Compiling Part 'SquadExpansion/Serenity/Parts/Structural/gripPads/sGripPad/sGripPad'

**Comment by sidrus** [comment]
Sounds like you made some progress.  Once loaded, were you able to click the part and open the browser window showing the Telemachus web UI?

**Comment by cheezecakes** [comment]
Corrrection, i tested with a clean working install and the mod still stalls the loading of the game. i guess (not a coder, just someone who loves this mod) there's a conflict with the breaking ground dlc seeing as it hangs up on the grip pad load.

**Comment by StoneBlue** [comment]
Hmm.. i would remove Telemachus 1.7.56, and try the new .64 version Sidrus just posted this AM...
Its weird tho, idk what telemachus could have to do with a stock part from a DLC? vOv

**Comment by cheezecakes** [comment]
Neither do i, just love the mod and would like it to not break my game lol!

**Comment by cheezecakes** [comment]
Just tried, keeps stalling out during game load.

**Comment by sidrus** [comment]
hmm.. might be a .Net version issue with the mod.  I'll put a build together later tonight after work and see if it fixes things.  Hopefully we can get this resolved for you soon!

**Comment by cheezecakes** [comment]
I tried downloading the breaking ground DLC from the ksp store, reinstalled it over the steam version, and now, it get's past the grip pad but stalls on the grip tape. I'll try and overwrite the steam ksp game folder with a version from the ksp store and reinstall the dlcs to see what happens. brb.

**Comment by cheezecakes** [comment]
ok, i deleted all game data folder, overwrote steamapps/common/kerbal space program with installers downloaded from ksp store, rebooted, including DLCs, game worked, installed newest version of telemachus to game, game still times out during loading.

**Comment by sidrus** [comment]
Would you mind testing a development build for me?  All you should have to do is delete the Telemachus folder in your GameData directory and copy over the Telemachus folder from this zip.

[GameData.zip](https://github.com/TeleIO/Telemachus-1/files/4446253/GameData.zip)

**Comment by cheezecakes** [comment]
Thank you kind sir, i have just tried with a clean install and it is still stalling at gripstrip on loading screen.

**Comment by sidrus** [comment]
Unfortunately, I'm out of ideas for now.  We're on the same builds of everything, including DLCs, and I don't see this issue.  There must be some difference that we're overlooking.  I will have to dig into this a bit later tonight when I'm off of work.

**Comment by Row-Bear** [comment]
I had a look in my Player.log file.
Interestingly enough, right after the sGripStrip model, it loads the Telemachus Blade model..
Both on 1.8.1 and 1.9.1 this is the order of model loading.

I don't know what it means, but it may mean something.

```
Load(Model): SquadExpansion/Serenity/Parts/Structural/gripPads/Assets/sGripStrip
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

Load(Model): Telemachus/Parts/Telemach_Blade/Telemach_Blade
```

**Comment by cheezecakes** [comment]
I ve reinstalled breaking ground dlc over the ksp with telemachus (release from above comments)
 installed and it seems to work 50% of the time. It slows right down at the main menu load and sometimes crashes. i ve started up ksp 4 times to check.

**Comment by sidrus** [comment]
Interesting -- this is helpful information.  I appreciate the help!

**Comment by cheezecakes** [comment]
Itès been consistently loading properly for the last couple of start-ups.

**Comment by sidrus** [comment]
Hi Cheezecakes - just wanted to follow up and see if things are still loading for you.  If so, I'll go ahead and close this ticket.

**Comment by cheezecakes** [comment]
I’m troubleshooting some connection issues with a second laptop and an ipad. Is there a how to for networks and connections?

**Comment by sidrus** [comment]
I actually have an open ticket to do a write up for exactly what you're asking :) Here's a short version:

1. All of your computers need to be on the same network (if you can ping the machines, you should be good)*
2. Start Telemachus on your KSP machine.
3. Find the IP address of your KSP machine (`ifconfig` on Linux/Mac or `ipconfig` on Windows)
4. Use the IP from step 3 in all of your other computers on the LAN

For example, if your Telemachus machine (the one running KSP) has an IP of `1.2.3.4` and you're using the default port configuration, then you'd put `http://1.2.3.4:8085` into all your web browsers.

*If you want to access this outside of your local network, you'll need to use a tool like [ngrok](https://ngrok.com/) or configure your router for port forwarding from the internet side of your network to your KSP machine.

**Comment by StoneBlue** [comment]
You can also change a few settings from default, for the LAN access in the XML file:
https://github.com/KSP-Telemachus/Telemachus/wiki/Configuration-File

**Comment by sidrus** [comment]
Hi Cheezecakes!  I'm going to close this issue at this time, as it seems we got the original issue mitigated.  If you're still having troubles connecting via a second device, I'd like to capture that in a separate ticket.
