### ISSUE TITLE
Set main branch to Develop

### ISSUE THREAD

**Issue by sidrus** [TeleIO/Telemachus-1#46]
@dsolmann I would like recommend we dust off the develop branch and use that as our primary PR merging branch.  This will allow us to catch potential issues with merges prior to triggering a release to all the delivery platforms.

Additionally, it would allow us to expose development builds to those who want to assist with testing changes.  Then, when the content seems right and we have good feedback from testing, we then merge to master and which triggers a release to the delivery platforms.

**Comment by dsolmann** [comment]
OK, changing

**Comment by dsolmann** [comment]
Done!
