### ISSUE TITLE
Various display issues with sensor readings

### ISSUE THREAD

**Issue by Row-Bear** [TeleIO/Telemachus-1#51]
Telemachus 1.7.64

-Temperature is displayed as Celsius on the webpage, but the value shown is in Kelvin.
-Temperature shows 3 decimal places on webpage, in game has 2
-The G-Force and Acceleration sensor output show 5 decimal places, the sensors in game show 2 decimals

![image](https://user-images.githubusercontent.com/60758353/79081532-988ba180-7d1e-11ea-85a5-efff24fac3ed.png)

**Comment by Row-Bear** [comment]
Update to add: the pressure sensor data is also displayed incorrectly. 
KSP shows the data in kPa, Telemachus uses Pa as unit and divides the value by 1000.
So, 100.1 kPa in game gets reported in Telemachus as 0.1001 Pa

**Comment by StoneBlue** [comment]
Not sure if this is the best ticket to post this to, but...
It seems depending on what resource tanks/capacities are actually present on the craft, or NOT, this is what gets displayed for empty/non-existant tanks/capacities:
resources display -1.00000 for resource tanks not present on craft
resources display  0.00000 for resource tanks present but empty

Probably not a big deal, just an FYI incase someone wants to address it.

**Comment by Row-Bear** [comment]
I'll make a PR to set the decimals to 2, as that is actually used.
The 0 / -1 issue is a bit more complex and will require bigger changes that would be better done after some overhauls Sidrus is planning

**Comment by sidrus** [comment]
@Row-Bear looks like your latest PR will close this ticket.  I've linked it and will merge the the PR.  Thanks for the help!
