### ISSUE TITLE
Sensors not working

### ISSUE THREAD

**Issue by dchaves80** [TeleIO/Telemachus-1#6]
![imagen](https://user-images.githubusercontent.com/16888179/51806049-cb4d9500-2253-11e9-93ba-63db819600fc.png)

**Comment by StoneBlue** [comment]
I can confirm that the readings from the four stock scince instruments are not being displayed, even tho the parts are being detected by Telemachus.

**Comment by StoneBlue** [comment]
This is still an issue with the 1.8.1 build... just wondering if this could be made a priority, since I, for one, heavily rely on Telemachus for live science data quite heavily... vOv

**Comment by Row-Bear** [comment]
I've tried (and failed so far) to tackle this.
By liberally sprinkling PluginLogger.debug(); through the sensor related code, I've found the following:
DataLinkHandlers.cs is able to find the sensors and also read their values `PluginLogger.debug(module.readoutInfo)`.

DataLinkFormatters however tries to build a list of sensors: `List<ModuleEnviroSensor> sensors = (List<ModuleEnviroSensor>)input; `but that results in an empty list. A bit later it checks for:
` if (sensors.Count == 0)` which evaluates as true and adds a 0 value for sensors.

I could not get the list of sensors to populate.
I'll try some older versions when I have time, to see if anything changed.

Update: In KSP 1.4.5 the issue also occurs for me. Earlier builds I could not get to compile.
The input passed to line 191 of DataLinkFormatters.cs is System.Collections.Generic.List`1[ModuleEnviroSensor] but the list of sensors it makes from it remains empty.

**Comment by StoneBlue** [comment]
@Row-Bear Any chance you tried converting the float values to doubles?
I'm not a coder, by far, but I've recently poked a couple plugins, and I've seen quite a few older things that were floats, now obsoleted, and needing to be doubles. vOv

Also, I've looked at that chunk of code in sources from KSP 1.2.2 to the most recent on the repo, and it looks like nothing in that chunk has changed.

**Comment by sidrus** [comment]
The issue was this line: `string ID = dataSources.args[0].ToLowerInvariant();`

That was dropping the ID to lower case, but the sensors are all in upper case.

**Comment by sidrus** [comment]
One thing I did notice while testing is that if I rejoin a game and jump into a vessel, I have to toggle the sensors off then back on to get them to start reporting data.  That's a bit inconvenient and I'm not entirely sure why that is right now.  I'll have to dig into that a bit more.

At least for now there's a workaround.
