### ISSUE TITLE
Update information.html credits section

### ISSUE THREAD

**Issue by Row-Bear** [TeleIO/Telemachus-1#63]
Currently it reads:

> Telemachus and Server Plugins - Rich
> Graphs - alexmun
> Telemachus Antenna Part - Borklund
> FusTek Telemachus Antenna - Fusty
> Map Data - Kerbal Maps
> Contributors - uffefl
> Testing - sal_vager

Main concern is that it links to www.kerbalmaps.com which is no longer active.
I created a PR with update to information.html

**Comment by dsolmann** [comment]
closed in #64
